version: '3'
services:
  emiloo-website:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    networks:
      - nginx-proxy-network

networks:
  nginx-proxy-network:
    external: true
