version: '3'
services:
  emiloo-homepage:
    build: .
    container_name: emiloo-homepage
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    networks:
      - nginx-proxy-network

networks:
  nginx-proxy-network:
    external: true
