version: '3'
services:
  emiloo-homepage:
    build: .
    image: emiloo/homepage:latest
    container_name: emiloo-homepage
    ports:
      - "5000:5000"
    networks:
      - nginx-proxy-network

networks:
  nginx-proxy-network:
    external: true
