version: '3'
services:
  vue-app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    networks:
      - nginx-proxy-network

networks:
  nginx-proxy-network:
    external: true
