name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push Docker image
      run: |
        docker buildx build --platform linux/amd64,linux/arm64 -t your-dockerhub-username/emiloo-website:latest --push .
    
    - name: Deploy to Server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa user@your-server-ip << 'EOF'
          docker pull your-dockerhub-username/emiloo-website:latest
          docker stop emiloo-container || true
          docker rm emiloo-container || true
          docker run -d -p 5000:5000 --name emiloo-container emiloo/emiloo-website:latest
        EOF
